# Generated by Django 3.2.13 on 2022-05-31 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plain_Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'ชาย ♂'), ('female', 'หญิง ♀')], max_length=20)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_shirt', models.ImageField(default='default.png', upload_to='clothing_store/static/img/shirt/')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothing_store.pattern')),
                ('plain_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothing_store.plain_color')),
            ],
        ),
    ]
